services:
  mongo-db:
    container_name: "mongo-db"
    image: mongo:${MONGO_VERSION}
    command: [
      --replSet, rs1,
      --bind_ip_all,
      --port, "27017"
    ]
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(
        mongosh
          --port 27017
          --quiet
          --eval
          "
            try {
              rs.initiate({ _id:'rs1', members:[ { _id:0, host:'mongo-db:27017' } ]  })
            } catch(e) {
              rs.status().ok
            }
          "
        ) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - ./mongo-storage:/data/db
    restart: "always"

  mongo-db-importer:
    container_name: "mongo-db-importer"
    image: mongo:${MONGO_VERSION}
    depends_on:
      mongo-db:
        condition: service_healthy
    environment:
      - MONGO_SERVICE=mongo-db
      - MONGO_PORT=27017
      - MONGO_UPDATE=true
    volumes:
      - ./mongo-dump:/mongo-dump
      - ./mongo-db-importer.sh:/run.sh
    command: ./run.sh
